/**
 * Hand-maintained AI metadata for the landing-page block vocabulary.
 *
 * Split out of catalog.ts so it is importable from pure-data contexts — in
 * particular `scripts/gen-puck-fields-manifest.ts`, which mirrors it into
 * `mcp-server/src/landing/catalog-meta.generated.ts` (the MCP server is built
 * and deployed standalone and cannot import files from this repo). Keep this
 * module free of imports beyond types: no React, no Puck, no @json-render.
 */

/**
 * Structural/primitive components that exist for human composition in Puck but should not be
 * generated by the AI as standalone page sections. Excluding them keeps the AI prompt focused
 * on real, self-contained landing sections.
 */
export const EXCLUDED_COMPONENTS: readonly string[] = [
  'Section',
  'Container',
  'Columns',
  'Grid',
  'Card',
  'Spacer',
  'Divider',
  'IconBlock',
  'BadgeBlock',
]

/** AI guidance per component. Keys must match component names in puckConfig.components. */
export const COMPONENT_DESCRIPTIONS: Record<string, string> = {
  // Primitives (usable on their own)
  Heading: 'A standalone heading/title. Use sparingly between sections, not as a full section.',
  TextBlock: 'A standalone paragraph of body text.',
  Image: 'A standalone image.',
  ButtonBlock: 'A standalone call-to-action button.',
  Video: 'An embedded video (YouTube/Vimeo/file URL).',
  // LMS / marketing sections (the AI should mostly use these)
  HeroBlock:
    'Top-of-page hero banner with a large headline, subtitle, and up to two CTA buttons. Use as the FIRST block of almost every page.',
  FeaturesGrid:
    'A grid of features/benefits, each with an icon, title, and description. Use to explain what the course/school offers.',
  CourseGrid:
    "A grid of the tenant's real courses (data-bound). Use when the page should showcase actual courses. Leave courseIds empty so it shows the latest published courses — do NOT invent course IDs; curation is a human-only step.",
  PricingTable: 'Side-by-side pricing plans with features and CTAs.',
  TestimonialGrid: 'A grid of student testimonials with name, role, and quote.',
  FaqAccordion: 'An expandable FAQ accordion. Good general-purpose FAQ.',
  FaqSplit: 'A two-column FAQ: heading on the left, questions on the right.',
  StatsCounter: 'A row of key statistics (value + label).',
  StatsBand:
    'A horizontal band of headline statistics with an optional heading/subtitle. Use for social proof.',
  AnimatedStats:
    'Statistics that count up on scroll into view; each has a numeric value plus prefix/suffix.',
  CtaBlock: 'A call-to-action section with heading and button(s).',
  CtaBanner:
    'A centered closing call-to-action banner with heading, subtitle, and one or two buttons. Use as the LAST block to drive sign-ups.',
  ContactForm: 'A contact form section.',
  LogoCloud: 'A static row of partner/brand logos for trust.',
  LogoMarquee: 'An animated, infinitely-scrolling row of partner/brand logos.',
  Banner: 'A thin announcement/promo banner, often near the top.',
  TeamGrid: 'A grid of team members/instructors with photo, name, and role.',
  ImageGallery: 'A gallery of images.',
  SocialProof: 'A social-proof strip (ratings, counts, short quotes).',
  EnrollCta:
    'A single-course call-to-action band with a headline, subtext, and an enroll button. Leave courseId empty (you cannot know real course IDs) — it then links to the full catalog; targeting a specific course is a human-only step.',
  CatalogBrowser:
    "A filterable, paginated browser over the tenant's real courses with search and an All/Free/Paid filter. Use when the page should let visitors explore the whole catalog.",
  ShinyEyebrow:
    'A small animated eyebrow/announcement label, placed above a hero headline.',
  ContentFeature:
    'A text + image content section with an optional pull-quote; image can be on the left or right.',
  // Navigation
  Header: 'A page header with logo and nav links.',
  Footer: 'A page footer with link columns and copyright.',
  Navbar: 'A navigation bar.',
  BreadcrumbBlock: 'A breadcrumb trail.',
}
