/**
 * AI metadata for the landing-page block vocabulary, in the shape the json-render pipeline
 * and the MCP mirror (`mcp-server/src/landing/catalog-meta.generated.ts`) read.
 *
 * The source of truth is now the annotation side-map `lib/puck/ai-annotations/` (Page
 * Architect); this module only re-derives the two legacy views from it so old readers keep
 * working until WP7 retires them. Keep it import-free beyond the pure-data annotations: no
 * React, no Puck, no @json-render.
 */
import { AI_ANNOTATIONS, SHARED_FIELDS_KEY } from '../puck/ai-annotations'

const COMPONENT_ENTRIES = Object.entries(AI_ANNOTATIONS).filter(([name]) => name !== SHARED_FIELDS_KEY)

/**
 * Structural/primitive components that exist for human composition in Puck but should not be
 * generated by the AI as standalone page sections.
 */
export const EXCLUDED_COMPONENTS: readonly string[] = COMPONENT_ENTRIES.filter(([, a]) => a.exclude).map(
  ([name]) => name
)

/** AI guidance per component. Keys match component names in puckConfig.components. */
export const COMPONENT_DESCRIPTIONS: Record<string, string> = Object.fromEntries(
  COMPONENT_ENTRIES.filter(([, a]) => !a.exclude).map(([name, a]) => [name, a.instructions])
)
