/**
 * json-render catalog for the landing-page builder — derived from the Puck config.
 *
 * This is the AI-facing *vocabulary*: which landing-page blocks an LLM may use, with typed
 * props and descriptions that guide generation. Rather than hand-maintaining a parallel
 * definition, every component's props schema is generated from its Puck `fields` via
 * `puckFieldsToZod` (see ADR 0001). So `lib/puck/config.ts` is the single source of truth for
 * BOTH the human editor and the AI generator — they cannot drift.
 *
 * The only thing not derivable from Puck is the AI guidance text, so we keep a description
 * map here. Components without a description are still included (with a generic note) unless
 * listed in EXCLUDED — pure structural/primitive blocks that an LLM should not emit as
 * top-level page sections (they're for humans composing layouts in Puck).
 */
import { defineCatalog } from '@json-render/core'
import { schema } from '@json-render/react/schema'
import { puckFieldsToZod } from './from-puck-fields'
// Pure-data field manifest generated from lib/puck/config.ts (the single source of truth).
// Imported instead of puckConfig so this catalog never bundles the client Puck editor tree
// (DropZone etc.) into server contexts like the /api/landing/generate route.
// Regenerate with: npx tsx scripts/gen-puck-fields-manifest.ts
import manifest from './puck-fields.generated.json'

/**
 * Structural/primitive components that exist for human composition in Puck but should not be
 * generated by the AI as standalone page sections. Excluding them keeps the AI prompt focused
 * on real, self-contained landing sections.
 */
const EXCLUDED = new Set<string>([
  'Section',
  'Container',
  'Columns',
  'Grid',
  'Card',
  'Spacer',
  'Divider',
  'IconBlock',
  'BadgeBlock',
])

/** AI guidance per component. Keys must match component names in puckConfig.components. */
const DESCRIPTIONS: Record<string, string> = {
  // Primitives (usable on their own)
  Heading: 'A standalone heading/title. Use sparingly between sections, not as a full section.',
  TextBlock: 'A standalone paragraph of body text.',
  Image: 'A standalone image.',
  ButtonBlock: 'A standalone call-to-action button.',
  Video: 'An embedded video (YouTube/Vimeo/file URL).',
  // LMS / marketing sections (the AI should mostly use these)
  HeroBlock:
    'Top-of-page hero banner with a large headline, subtitle, and up to two CTA buttons. Use as the FIRST block of almost every page.',
  FeaturesGrid:
    'A grid of features/benefits, each with an icon, title, and description. Use to explain what the course/school offers.',
  CourseGrid:
    'A grid of the tenant\'s real courses (data-bound). Use when the page should showcase actual courses. Leave courseIds empty so it shows the latest published courses — do NOT invent course IDs; curation is a human-only step.',
  PricingTable: 'Side-by-side pricing plans with features and CTAs.',
  TestimonialGrid: 'A grid of student testimonials with name, role, and quote.',
  FaqAccordion: 'An expandable FAQ accordion. Good general-purpose FAQ.',
  FaqSplit: 'A two-column FAQ: heading on the left, questions on the right.',
  StatsCounter: 'A row of key statistics (value + label).',
  StatsBand:
    'A horizontal band of headline statistics with an optional heading/subtitle. Use for social proof.',
  AnimatedStats:
    'Statistics that count up on scroll into view; each has a numeric value plus prefix/suffix.',
  CtaBlock: 'A call-to-action section with heading and button(s).',
  CtaBanner:
    'A centered closing call-to-action banner with heading, subtitle, and one or two buttons. Use as the LAST block to drive sign-ups.',
  ContactForm: 'A contact form section.',
  LogoCloud: 'A static row of partner/brand logos for trust.',
  LogoMarquee: 'An animated, infinitely-scrolling row of partner/brand logos.',
  Banner: 'A thin announcement/promo banner, often near the top.',
  TeamGrid: 'A grid of team members/instructors with photo, name, and role.',
  ImageGallery: 'A gallery of images.',
  SocialProof: 'A social-proof strip (ratings, counts, short quotes).',
  ShinyEyebrow:
    'A small animated eyebrow/announcement label, placed above a hero headline.',
  ContentFeature:
    'A text + image content section with an optional pull-quote; image can be on the left or right.',
  // Navigation
  Header: 'A page header with logo and nav links.',
  Footer: 'A page footer with link columns and copyright.',
  Navbar: 'A navigation bar.',
  BreadcrumbBlock: 'A breadcrumb trail.',
}

// Build the catalog components map from the Puck config.
const components: Record<
  string,
  { description: string; props: ReturnType<typeof puckFieldsToZod> }
> = {}

for (const [name, entry] of Object.entries(manifest)) {
  if (EXCLUDED.has(name)) continue
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const fields = (entry as any).fields as Record<string, any> | undefined
  components[name] = {
    description: DESCRIPTIONS[name] ?? `The ${name} landing-page block.`,
    props: puckFieldsToZod(fields),
  }
}

export const landingCatalog = defineCatalog(schema, {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  components: components as any,
  actions: {},
})

export type LandingCatalog = typeof landingCatalog

/** Names the AI may generate (everything in the catalog). Useful for tests/UI hints. */
export const CATALOG_COMPONENT_NAMES = Object.keys(components)

/**
 * Each component's Puck `defaultProps`, keyed by component name. The bridge merges these
 * UNDER the AI-supplied props so a generated block always has its required arrays/values even
 * when the model omits them — Puck's `Render` does not reliably backfill defaults for
 * top-level props, so a missing array would otherwise crash a block at `items.length`.
 * Derived from the same manifest as the catalog, so it stays in sync with lib/puck/config.ts.
 */
export const DEFAULT_PROPS_BY_TYPE: Record<string, Record<string, unknown>> = {}
for (const [name, entry] of Object.entries(manifest)) {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  DEFAULT_PROPS_BY_TYPE[name] = ((entry as any).defaultProps ?? {}) as Record<string, unknown>
}
