import Head from "next/head";
import HomeBanner from "../components/home/HomeBanner";
import AboutUs from "../components/home/AboutUs";
import PlanCard, { type PlanCardProps } from "../components/home/PlanCard";
import Subscribe from "../components/home/Subscribe";
import FAQs from "../components/home/FAQs";
import Features from "../components/home/Features";
import Layout from "../components/Layout/Layout";
import axios from "axios";
import { Category, Course, Media, Plan, Product } from "../payload-types";
import { IndexPageRef, PaginatedDocs } from "../utils/types/common";
import { forwardRef } from "react";
import PageTransition from "../components/PageTransition";
import { apiUrl } from "../utils/env";


type HomeProps = {
    data: Product[]
};
function Home (props: HomeProps, ref: IndexPageRef) {

    const { data } = props;

    if (!data) {
        return <div>Loading...</div>;
    }

    
    const cardData = data.map((doc) => {
        console.log(doc)
      const imgUrl = doc.productImage as Media
      const imageAlt = doc.productImage as Media
      const relation = doc.productType?.relationTo 
      const categorysToChoose = {
        courses: doc.productType?.value as Course,
        plans: doc.productType?.value as Plan
      }
      const categorysData = categorysToChoose[relation as keyof typeof categorysToChoose]
      const categorys = categorysData.category?.map((cat) => {
        const a = cat as Category
        return a.name
      }) 
        return {
            id: doc.id,
            title: doc.name,
            isNew: true,
            description: doc.description,
            imgUrl: imgUrl?.url as string,
            categorys: categorys,
            imageAlt: imageAlt?.altText as string,
        };
    });

    return (
        <>
            <Head>
                <title>LMS</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <PageTransition ref={ref}>
                <Layout>
                    <main className="flex min-h-screen w-full flex-col items-center justify-center bg-base-200">
                        <HomeBanner />
                        <div className="flex w-full flex-wrap items-center justify-around gap-4 bg-base-200 px-10 py-16">
                            {cardData.map(planCard => (
                                <PlanCard key={planCard.id} {...planCard as PlanCardProps} />
                            ))}
                        </div>
                        <AboutUs />
                        <Features />
                        <Subscribe />
                        <FAQs />
                    </main>
                </Layout>
            </PageTransition>
        </>
    );
}

export async function getStaticProps() {

    try{
        const response = await axios.get<PaginatedDocs<Product>>(apiUrl + '/api/products/', {
            // Make sure to include cookies with fetch
            // withCredentials: true,
        })

        console.log(response.data)

        return {
            props: {
                data: response.data.docs
            }, // will be passed to the page component as props
        }
    } catch (error) {

        console.log(error)
        return {
            props: {
                data: null
            }, // will be passed to the page component as props
        }
    }
}

export default forwardRef(Home);