import Head from "next/head";
import HomeBanner from "../components/home/HomeBanner";
import Header from "../components/Header/Header";
import Footer from "../components/Footer/Footer";
import AboutUs from "../components/home/AboutUs";
import PlanCard, { type PlanCardProps } from "../components/home/PlanCard";
import Subscribe from "../components/home/Subscribe";
import FAQs from "../components/home/FAQs";
import Features from "../components/home/Features";

type HomeProps = {
    cards: PlanCardProps[];
};

const PlanCardsList: PlanCardProps[] = [
  // {
  //     title: "Plan 1",
  //     isNew: true,
  //     categorys: ["Category 1", "Category 2"],
  //     description:
  //         "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl nec ultricies lacinia, nunc est ultricies nisl, nec ultricies nisl nunc et nisl. Sed euismod, nisl nec ultricies lacinia, nunc est ultricies nisl, nec ultricies nisl nunc et nisl.",
  //     imgUrl: "/icons/instant_support.svg",
  //     imageAlt: "Plan 1",
  // },
  {
      title: "Plan 2",
      isNew: false,
      categorys: ["Category 1", "Category 2"],
      description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl nec ultricies lacinia, nunc est ultricies nisl, nec ultricies nisl nunc et nisl. Sed euismod, nisl nec ultricies lacinia, nunc est ultricies nisl, nec ultricies nisl nunc et nisl.",
      imgUrl: "/icons/undraw_online_learning.svg",
      imageAlt: "Plan 2",
  },
  {
      title: "Plan 3",
      isNew: false,
      categorys: ["Category 1", "Category 2"],
      description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl nec ultricies lacinia, nunc est ultricies nisl, nec ultricies nisl nunc et nisl. Sed euismod, nisl nec ultricies lacinia, nunc est ultricies nisl, nec ultricies nisl nunc et nisl.",
      imgUrl: "/icons/conference.svg",
      imageAlt: "Plan 3",
  },
  {
      title: "Plan 4",
      isNew: false,
      categorys: ["Category 1", "Category 2"],
      description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl nec ultricies lacinia, nunc est ultricies nisl, nec ultricies nisl nunc et nisl. Sed euismod, nisl nec ultricies lacinia, nunc est ultricies nisl, nec ultricies nisl nunc et nisl.",
      imgUrl: "/icons/undraw_education.svg",
      imageAlt: "Plan 4",
  },
];

export default function Home ({
    cards,
}: HomeProps) {
    
    return (
        <>
            <Head>
                <title>LMS</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main className="flex min-h-screen w-full flex-col items-center justify-center bg-base-200">
                <HomeBanner />
                <div className="flex w-full flex-wrap items-center justify-around gap-4 bg-base-200 px-10 py-16">
                    {cards.map((planCard, index) => (
                        <PlanCard key={index} {...planCard} />
                    ))}
                </div>
                <AboutUs />
                <Features />
                <Subscribe />
                <FAQs />
            </main>
            <Footer />
        </>
    );
}

export async function getStaticProps() {

  return {
    props: {
      cards: PlanCardsList,
    },
  };

    // const products = await prisma.products.findMany({
    //     // where: {
    //     //     productType: {
    //     //         relationTo: "plans"
    //     //     }
    //     // }
    // });

    // const productsImages = await prisma.medias.findMany({
    //     where: {
    //         id: {
    //             in: products.map((product) => product.productImage)
    //         }
    //     }
    // });

    // const urls = productsImages.map((image) => `${env.LMS_URL}/media/${image.filename}`);

    // const cards = products.map((product, index) => {
    //     return {
    //         title: product.name,
    //         isNew: false,
    //         description: product.description,
    //         imgUrl: urls[index],
    //         imageAlt: product.name,
    //     }
    // });

    // return {
    //     props: {
    //         cards
    //     },
    // };
}