/**
 * Generates the block vocabulary for the shared Page Architect core (`@lms/core` page-builder):
 *   - packages/core/src/page-builder/generated/manifest.generated.ts — every Puck component's
 *     fields, defaultProps and category, plus the folded `lib/puck/ai-annotations/` entries;
 *   - packages/core/src/page-builder/generated/templates.generated.ts — every PUCK_TEMPLATE
 *     with its id, pageType, block sequence and puck_data.
 *
 * Why: the web agent route, the editor applier and the MCP server all validate and apply ops
 * on the server, where importing `lib/puck/config.ts` would bundle the whole client Puck
 * editor tree. These files are plain data, so `lib/puck/config.ts` stays the single source of
 * truth without ever being imported server-side.
 * Generated files are never hand-merged: after any merge, re-run this script.
 *
 * Run: npm run gen:puck-fields  (= npx tsx scripts/gen-puck-fields-manifest.ts)
 * Re-run whenever a component's fields, an ai-annotation or a template changes.
 */
import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { puckConfig } from '../lib/puck/config'
import { AI_ANNOTATIONS, SHARED_FIELDS_KEY, type AiComponentAnnotation } from '../lib/puck/ai-annotations'
import { PUCK_TEMPLATES } from '../lib/puck/templates'

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AnyFields = Record<string, any>

interface ManifestEntry {
  category: string | null
  fields: AnyFields
  // Each component's Puck defaultProps (serializable). `add` ops merge these under the
  // AI-supplied props so a block always has its required arrays/values even when the model
  // omits them — preventing render crashes like `items.length` on undefined.
  defaultProps: AnyFields
}

// Reverse-map component name → category from the config's categories.
const categoryOf: Record<string, string> = {}
for (const [cat, def] of Object.entries(puckConfig.categories ?? {})) {
  for (const name of (def as { components?: string[] }).components ?? []) {
    categoryOf[name] = cat
  }
}

const manifest: Record<string, ManifestEntry> = {}
for (const [name, def] of Object.entries(puckConfig.components)) {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const fields = ((def as any).fields ?? {}) as AnyFields
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const defaultProps = ((def as any).defaultProps ?? {}) as AnyFields
  // Strip non-serializable bits (functions like custom field renderers) — keep only the
  // declarative shape the catalog needs: type, label, options, arrayFields.
  manifest[name] = {
    category: categoryOf[name] ?? null,
    fields: pruneFields(fields),
    // JSON round-trip drops any non-serializable defaults (none expected) and gives us a
    // clean plain-data copy.
    defaultProps: JSON.parse(JSON.stringify(defaultProps)),
  }
}

function pruneFields(fields: AnyFields): AnyFields {
  const out: AnyFields = {}
  for (const [k, f] of Object.entries(fields)) {
    if (!f || typeof f !== 'object') continue
    const entry: AnyFields = { type: f.type }
    if (typeof f.label === 'string') entry.label = f.label
    if (Array.isArray(f.options)) {
      entry.options = f.options
        .filter((o: unknown) => o && typeof o === 'object')
        .map((o: { label?: unknown; value?: unknown }) => ({ label: o.label, value: o.value }))
    }
    if (f.arrayFields && typeof f.arrayFields === 'object') {
      entry.arrayFields = pruneFields(f.arrayFields)
    }
    if (f.defaultItemProps && typeof f.defaultItemProps === 'object') {
      entry.defaultItemProps = JSON.parse(JSON.stringify(f.defaultItemProps))
    }
    out[k] = entry
  }
  return out
}

const GENERATED_HEADER =
  '// AUTO-GENERATED by scripts/gen-puck-fields-manifest.ts (run from the repo root:\n' +
  '// npx tsx scripts/gen-puck-fields-manifest.ts). Do NOT edit by hand.\n\n'

// mcp-server reads the core files below through `@lms/core`.

// ── Page Architect core (packages/core/src/page-builder/generated) ───────────────────
// The shared page-builder core (web route, editor applier, MCP) reads the block vocabulary
// and the templates from these two files. The manifest folds the AI annotation side-map
// (lib/puck/ai-annotations/) into each entry; the `'*'` entry becomes `shared`.
const CORE_GENERATED_DIR = resolve(__dirname, '../packages/core/src/page-builder/generated')

function pruneAnnotation(a: AiComponentAnnotation | undefined, fields: AnyFields) {
  if (!a) return undefined
  const out: AiComponentAnnotation = { instructions: a.instructions ?? '' }
  if (a.exclude) out.exclude = true
  if (a.zones?.length) out.zones = [...a.zones]
  const aiFields = Object.entries(a.fields ?? {}).filter(([key]) => {
    const top = key.split('.')[0]
    if (fields[top]) return true
    console.warn(`ai-annotations: ${key} is not a field of this block — ignored`)
    return false
  })
  if (aiFields.length) out.fields = Object.fromEntries(aiFields)
  return out
}

const coreComponents: Record<string, ManifestEntry & { ai?: AiComponentAnnotation }> = {}
for (const [name, entry] of Object.entries(manifest)) {
  const ai = pruneAnnotation(AI_ANNOTATIONS[name], entry.fields)
  coreComponents[name] = ai ? { ...entry, ai } : entry
}
for (const name of Object.keys(AI_ANNOTATIONS)) {
  if (name !== SHARED_FIELDS_KEY && !manifest[name]) console.warn(`ai-annotations: unknown block ${name} — ignored`)
}
const shared = AI_ANNOTATIONS[SHARED_FIELDS_KEY] ?? { instructions: '' }
const rootDef = (puckConfig.root ?? {}) as { fields?: AnyFields; defaultProps?: AnyFields }
const coreManifest = {
  components: coreComponents,
  shared: { instructions: shared.instructions ?? '', fields: shared.fields ?? {} },
  // Page-level root props (SEO), validated by catalog.validateRoot for update_root.
  root: {
    fields: pruneFields(rootDef.fields ?? {}),
    defaultProps: JSON.parse(JSON.stringify(rootDef.defaultProps ?? {})),
  },
}

const coreManifestTarget = resolve(CORE_GENERATED_DIR, 'manifest.generated.ts')
writeFileSync(
  coreManifestTarget,
  GENERATED_HEADER +
    "import type { PageBuilderManifest } from '../types'\n\n" +
    `export const PAGE_BUILDER_MANIFEST: PageBuilderManifest = ${JSON.stringify(coreManifest, null, 2)}\n`
)
console.log(`Wrote core manifest → ${coreManifestTarget}`)

const coreTemplates = PUCK_TEMPLATES.map((t) => ({
  id: t.id,
  name: t.name,
  description: t.description,
  category: t.category,
  pageType: t.pageType,
  sortOrder: t.sort_order,
  blocks: t.puck_data.content.map((item) => item.type),
  puck_data: JSON.parse(JSON.stringify(t.puck_data)),
}))
const templateIds = new Set<string>()
for (const t of coreTemplates) {
  if (!t.id || templateIds.has(t.id)) throw new Error(`Template "${t.name}" needs a unique id (got "${t.id}")`)
  templateIds.add(t.id)
}

const coreTemplatesTarget = resolve(CORE_GENERATED_DIR, 'templates.generated.ts')
writeFileSync(
  coreTemplatesTarget,
  GENERATED_HEADER +
    "import type { PageTemplate } from '../types'\n\n" +
    `export const PAGE_TEMPLATES: PageTemplate[] = ${JSON.stringify(coreTemplates, null, 2)}\n`
)
console.log(`Wrote ${coreTemplates.length} core templates → ${coreTemplatesTarget}`)
