/**
 * Generates lib/json-render/puck-fields.generated.json — a pure-data manifest of every Puck
 * component's `fields`, keyed by component name, plus its category.
 *
 * Why: the json-render catalog must derive its prop schemas from the Puck components' fields,
 * but it runs in a SERVER context (the /api/landing/generate route). Importing `lib/puck/config.ts`
 * there would bundle the entire client Puck editor tree (DropZone, etc.) into the server build
 * and fail. This manifest is plain JSON with no React imports, so the catalog can import it
 * anywhere safely — while `lib/puck/config.ts` stays the single source of truth.
 *
 * Run: npx tsx scripts/gen-puck-fields-manifest.ts
 * Re-run whenever a component's fields change (add to a precommit/CI step).
 */
import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { puckConfig } from '../lib/puck/config'
import { COMPONENT_DESCRIPTIONS, EXCLUDED_COMPONENTS } from '../lib/json-render/catalog-meta'
import { LANDING_PAGE_CRAFT_GUIDE } from '../lib/json-render/authoring-guide'

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AnyFields = Record<string, any>

interface ManifestEntry {
  category: string | null
  fields: AnyFields
  // Each component's Puck defaultProps (serializable). The bridge merges these under the
  // AI-supplied props so a generated block always has its required arrays/values even when
  // the model omits them — preventing render crashes like `items.length` on undefined.
  defaultProps: AnyFields
}

// Reverse-map component name → category from the config's categories.
const categoryOf: Record<string, string> = {}
for (const [cat, def] of Object.entries(puckConfig.categories ?? {})) {
  for (const name of (def as { components?: string[] }).components ?? []) {
    categoryOf[name] = cat
  }
}

const manifest: Record<string, ManifestEntry> = {}
for (const [name, def] of Object.entries(puckConfig.components)) {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const fields = ((def as any).fields ?? {}) as AnyFields
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const defaultProps = ((def as any).defaultProps ?? {}) as AnyFields
  // Strip non-serializable bits (functions like custom field renderers) — keep only the
  // declarative shape the catalog needs: type, label, options, arrayFields.
  manifest[name] = {
    category: categoryOf[name] ?? null,
    fields: pruneFields(fields),
    // JSON round-trip drops any non-serializable defaults (none expected) and gives us a
    // clean plain-data copy.
    defaultProps: JSON.parse(JSON.stringify(defaultProps)),
  }
}

function pruneFields(fields: AnyFields): AnyFields {
  const out: AnyFields = {}
  for (const [k, f] of Object.entries(fields)) {
    if (!f || typeof f !== 'object') continue
    const entry: AnyFields = { type: f.type }
    if (typeof f.label === 'string') entry.label = f.label
    if (Array.isArray(f.options)) {
      entry.options = f.options
        .filter((o: unknown) => o && typeof o === 'object')
        .map((o: { label?: unknown; value?: unknown }) => ({ label: o.label, value: o.value }))
    }
    if (f.arrayFields && typeof f.arrayFields === 'object') {
      entry.arrayFields = pruneFields(f.arrayFields)
    }
    out[k] = entry
  }
  return out
}

const target = resolve(__dirname, '../lib/json-render/puck-fields.generated.json')
writeFileSync(target, JSON.stringify(manifest, null, 2) + '\n')
console.log(`Wrote ${Object.keys(manifest).length} components → ${target}`)

// ── Mirror into the standalone MCP server ────────────────────────────────────
// mcp-server/ is built and deployed on its own (Docker context = ./mcp-server), so it
// cannot import anything from this repo. Its landing-page tools need the same block
// vocabulary; emit it as generated TS modules so the two surfaces cannot drift.
const GENERATED_HEADER =
  '// AUTO-GENERATED by scripts/gen-puck-fields-manifest.ts (run from the repo root:\n' +
  '// npx tsx scripts/gen-puck-fields-manifest.ts). Do NOT edit by hand.\n\n'

const mcpManifestTarget = resolve(__dirname, '../mcp-server/src/landing/puck-fields.generated.ts')
writeFileSync(
  mcpManifestTarget,
  GENERATED_HEADER +
    'export interface ManifestEntry {\n' +
    '  category: string | null\n' +
    '  // eslint-disable-next-line @typescript-eslint/no-explicit-any\n' +
    '  fields: Record<string, any>\n' +
    '  defaultProps: Record<string, unknown>\n' +
    '}\n\n' +
    `export const PUCK_FIELDS_MANIFEST: Record<string, ManifestEntry> = ${JSON.stringify(manifest, null, 2)}\n`
)
console.log(`Wrote MCP mirror → ${mcpManifestTarget}`)

const mcpMetaTarget = resolve(__dirname, '../mcp-server/src/landing/catalog-meta.generated.ts')
writeFileSync(
  mcpMetaTarget,
  GENERATED_HEADER +
    `export const EXCLUDED_COMPONENTS: readonly string[] = ${JSON.stringify(EXCLUDED_COMPONENTS, null, 2)}\n\n` +
    `export const COMPONENT_DESCRIPTIONS: Record<string, string> = ${JSON.stringify(COMPONENT_DESCRIPTIONS, null, 2)}\n\n` +
    `export const LANDING_PAGE_CRAFT_GUIDE = ${JSON.stringify(LANDING_PAGE_CRAFT_GUIDE)}\n`
)
console.log(`Wrote MCP catalog meta → ${mcpMetaTarget}`)
