-- Create lessons_ai_tasks table
CREATE TABLE IF NOT EXISTS lessons_ai_tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lesson_id BIGINT REFERENCES lessons(id) ON DELETE CASCADE,
  task_description TEXT NOT NULL,
  ai_instructions TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(lesson_id)
);

-- Create lessons_ai_task_messages table
CREATE TABLE IF NOT EXISTS lessons_ai_task_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lesson_id BIGINT REFERENCES lessons(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
  content TEXT NOT NULL,
  tool_calls JSONB,
  tool_invocations JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add RLS policies
ALTER TABLE lessons_ai_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE lessons_ai_task_messages ENABLE ROW LEVEL SECURITY;

-- lessons_ai_tasks policies
CREATE POLICY "Public read access for tasks" ON lessons_ai_tasks
  FOR SELECT USING (true); -- Or restricted to enrolled students

CREATE POLICY "Teachers can insert/update tasks" ON lessons_ai_tasks
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM lessons l
      JOIN courses c ON l.course_id = c.course_id
      WHERE l.id = lessons_ai_tasks.lesson_id
      AND c.author_id = auth.uid()
    )
  );

-- lessons_ai_task_messages policies
CREATE POLICY "Users can manage their own messages" ON lessons_ai_task_messages
  FOR ALL USING (auth.uid() = user_id);
