-- #396 Elo item difficulty + adaptive question selection.
--
-- Two ledgers, updated online on every recorded attempt:
--   item_ratings          — per-tenant difficulty of rateable "items". Real items are
--                           exercises and exam questions. Virtual 'topic' rows act as the
--                           difficulty anchor for LLM-generated practice questions, which
--                           have no persistent identity (they live as JSONB inside
--                           practice_attempts rows).
--   student_topic_ratings — per-student ability per topic string (the same free-text key
--                           every existing aggregation groups on: weak spots, exam
--                           readiness, the #393 interleaving gate).
--
-- Update hook: DB triggers, not the tool layer. Chosen because (a) the MCP server runs
-- every query with the caller's RLS-scoped token and holds no service-role data path, so
-- a student session cannot write shared rating rows from application code; (b) attempts
-- arrive via several independent paths (practice tool, exercise completion, AI exam
-- grading) that all converge at these inserts; (c) the rating update is atomic with the
-- attempt insert. Precedent: handle_practice_attempt_xp.
--
-- Known approximations (accepted):
--   * Re-grading that re-inserts exam_question_scores rows counts as a new match; K-decay
--     bounds the drift.
--   * Exercise/exam-question matches rate only the item side against the student's mean
--     topic rating (those rows carry no topic string), avoiding double-counting the
--     student, whose ability is learned from practice_attempts.

-- ============================================================================
-- Tables
-- ============================================================================

create table if not exists public.item_ratings (
  id            bigint generated by default as identity primary key,
  tenant_id     uuid        not null references public.tenants(id) on delete cascade,
  item_type     text        not null check (item_type in ('exercise', 'exam_question', 'topic')),
  item_id       bigint,
  topic         text,
  course_id     bigint,
  rating        numeric(7,2) not null default 1500,
  attempt_count integer     not null default 0,
  updated_at    timestamptz not null default now(),
  constraint item_ratings_identity_shape check (
    (item_type = 'topic' and topic is not null and item_id is null)
    or (item_type <> 'topic' and item_id is not null and topic is null)
  )
);

create unique index if not exists item_ratings_item_key
  on public.item_ratings (tenant_id, item_type, item_id)
  where item_id is not null;

create unique index if not exists item_ratings_topic_key
  on public.item_ratings (tenant_id, topic)
  where item_type = 'topic';

-- Adaptive selection scans a course's rated items ordered by rating distance.
create index if not exists item_ratings_selection_idx
  on public.item_ratings (tenant_id, course_id, item_type, rating);

create table if not exists public.student_topic_ratings (
  id            bigint generated by default as identity primary key,
  user_id       uuid        not null references auth.users(id) on delete cascade,
  tenant_id     uuid        not null references public.tenants(id) on delete cascade,
  topic         text        not null,
  course_id     bigint,
  rating        numeric(7,2) not null default 1500,
  attempt_count integer     not null default 0,
  updated_at    timestamptz not null default now(),
  constraint student_topic_ratings_key unique (user_id, tenant_id, topic)
);

create index if not exists student_topic_ratings_user_idx
  on public.student_topic_ratings (user_id, tenant_id);

-- ============================================================================
-- RLS — reads only; all writes go through the security-definer trigger functions.
-- ============================================================================

alter table public.item_ratings enable row level security;
alter table public.student_topic_ratings enable row level security;

-- Any active tenant member may read item difficulty (adaptive selection runs under the
-- student's own token). Membership comes from tenant_users bound to auth.uid(), never
-- from client-settable headers.
create policy tenant_members_view_item_ratings on public.item_ratings
  for select
  using (
    exists (
      select 1
      from public.tenant_users tu
      where tu.user_id = (select auth.uid())
        and tu.tenant_id = item_ratings.tenant_id
        and tu.status = 'active'
    )
  );

create policy students_view_own_topic_ratings on public.student_topic_ratings
  for select
  using (user_id = (select auth.uid()));

create policy teachers_view_tenant_topic_ratings on public.student_topic_ratings
  for select
  using (
    exists (
      select 1
      from public.tenant_users tu
      where tu.user_id = (select auth.uid())
        and tu.tenant_id = student_topic_ratings.tenant_id
        and tu.role in ('teacher', 'admin')
        and tu.status = 'active'
    )
  );

-- ============================================================================
-- Elo math helpers
-- ============================================================================

-- Expected score of `a` against `b` (standard logistic, 400 scale).
create or replace function public.elo_expected(a numeric, b numeric)
returns numeric
language sql
immutable
set search_path = ''
as $$
  select 1.0 / (1.0 + power(10.0, (b - a) / 400.0));
$$;

-- K decays with experience so early attempts move ratings fast and mature
-- ratings stabilize: 40 → 8 as attempt_count grows.
create or replace function public.elo_k(attempts integer)
returns numeric
language sql
immutable
set search_path = ''
as $$
  select greatest(8.0, 40.0 / (1.0 + attempts / 10.0));
$$;

-- ============================================================================
-- Core match update (security definer — the only write path to both tables)
-- ============================================================================

create or replace function public.elo_apply_match(
  _tenant_id uuid,
  _user_id uuid,
  _student_topic text,   -- topic key for the student ledger (null → skip student update)
  _course_id bigint,
  _item_type text,       -- 'topic' | 'exercise' | 'exam_question'
  _item_id bigint,       -- null for topic anchors
  _item_topic text,      -- topic string for anchor rows
  _score numeric         -- actual result in [0, 1] (fractional credit allowed)
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  _item public.item_ratings%rowtype;
  _student public.student_topic_ratings%rowtype;
  _student_rating numeric;
  _expected numeric;
  _s numeric := greatest(0.0, least(1.0, _score));
  _cold_start numeric;
begin
  -- Upsert + lock the item row. Cold start: real items inherit the course's average
  -- item rating (else 1500); topic anchors start at 1500.
  if _item_type = 'topic' then
    insert into public.item_ratings (tenant_id, item_type, topic, course_id)
    values (_tenant_id, 'topic', _item_topic, _course_id)
    on conflict (tenant_id, topic) where item_type = 'topic' do nothing;

    select * into _item from public.item_ratings
    where tenant_id = _tenant_id and item_type = 'topic' and topic = _item_topic
    for update;
  else
    select coalesce(avg(rating), 1500) into _cold_start
    from public.item_ratings
    where tenant_id = _tenant_id and course_id = _course_id and item_type = _item_type;

    insert into public.item_ratings (tenant_id, item_type, item_id, course_id, rating)
    values (_tenant_id, _item_type, _item_id, _course_id, _cold_start)
    on conflict (tenant_id, item_type, item_id) where item_id is not null do nothing;

    select * into _item from public.item_ratings
    where tenant_id = _tenant_id and item_type = _item_type and item_id = _item_id
    for update;
  end if;

  if _student_topic is not null then
    -- Student cold start: first rating for a topic initializes to the topic anchor's
    -- current value (≈ topic median), so expected success starts near 50%.
    insert into public.student_topic_ratings (user_id, tenant_id, topic, course_id, rating)
    values (_user_id, _tenant_id, _student_topic, _course_id, _item.rating)
    on conflict (user_id, tenant_id, topic) do nothing;

    select * into _student from public.student_topic_ratings
    where user_id = _user_id and tenant_id = _tenant_id and topic = _student_topic
    for update;

    _student_rating := _student.rating;
  else
    -- Item-only match: rate the item against the student's mean topic ability.
    select coalesce(avg(rating), 1500) into _student_rating
    from public.student_topic_ratings
    where user_id = _user_id and tenant_id = _tenant_id;
  end if;

  _expected := public.elo_expected(_student_rating, _item.rating);

  update public.item_ratings
  set rating = rating + public.elo_k(attempt_count) * (_expected - _s),
      attempt_count = attempt_count + 1,
      course_id = coalesce(course_id, _course_id),
      updated_at = now()
  where id = _item.id;

  if _student_topic is not null then
    update public.student_topic_ratings
    set rating = rating + public.elo_k(attempt_count) * (_s - _expected),
        attempt_count = attempt_count + 1,
        course_id = coalesce(_course_id, course_id),
        updated_at = now()
    where id = _student.id;
  end if;
end;
$$;

-- ============================================================================
-- Triggers — ratings are best-effort telemetry; never block the parent insert.
-- ============================================================================

create or replace function public.handle_practice_attempt_elo()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  _s numeric;
begin
  _s := coalesce(new.score, 0) / 100.0;

  -- Student topic rating vs the topic difficulty anchor. Mixed sessions are already
  -- split into one row per topic upstream (#393), so per-topic updates stay correct.
  perform public.elo_apply_match(
    new.tenant_id, new.user_id, new.topic, new.course_id,
    'topic', null, new.topic, _s
  );

  -- Drills sourced from a real exercise also rate that exercise (item side only).
  if new.source_exercise_id is not null then
    perform public.elo_apply_match(
      new.tenant_id, new.user_id, null, new.course_id,
      'exercise', new.source_exercise_id, null, _s
    );
  end if;

  return new;
exception when others then
  raise warning 'elo update failed for practice_attempt %: %', new.id, sqlerrm;
  return new;
end;
$$;

create trigger trg_practice_attempt_elo
  after insert on public.practice_attempts
  for each row execute function public.handle_practice_attempt_elo();

create or replace function public.handle_exercise_evaluation_elo()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  _s numeric;
  _course_id bigint;
begin
  _s := coalesce(new.score / 100.0, case when new.passed then 1.0 else 0.0 end);

  select course_id into _course_id from public.exercises where id = new.exercise_id;

  perform public.elo_apply_match(
    new.tenant_id, new.user_id, null, _course_id,
    'exercise', new.exercise_id, null, _s
  );

  return new;
exception when others then
  raise warning 'elo update failed for exercise_evaluation %: %', new.id, sqlerrm;
  return new;
end;
$$;

create trigger trg_exercise_evaluation_elo
  after insert on public.exercise_evaluations
  for each row execute function public.handle_exercise_evaluation_elo();

create or replace function public.handle_exam_question_score_elo()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  _s numeric;
  _student_id uuid;
  _tenant_id uuid;
  _course_id bigint;
begin
  -- exam_question_scores has no tenant_id (exam child tables never do — see CLAUDE.md);
  -- derive tenant/course through the submission's exam.
  select es.student_id, e.tenant_id, e.course_id
  into _student_id, _tenant_id, _course_id
  from public.exam_submissions es
  join public.exams e on e.exam_id = es.exam_id
  where es.submission_id = new.submission_id;

  if _tenant_id is null then
    return new;
  end if;

  if new.points_possible > 0 then
    _s := new.points_earned / new.points_possible;
  elsif new.is_correct is not null then
    _s := case when new.is_correct then 1.0 else 0.0 end;
  else
    return new;
  end if;

  perform public.elo_apply_match(
    _tenant_id, _student_id, null, _course_id,
    'exam_question', new.question_id, null, _s
  );

  return new;
exception when others then
  raise warning 'elo update failed for exam_question_score %: %', new.score_id, sqlerrm;
  return new;
end;
$$;

create trigger trg_exam_question_score_elo
  after insert on public.exam_question_scores
  for each row execute function public.handle_exam_question_score_elo();

-- Lock down: nothing calls these directly.
revoke execute on function public.elo_apply_match(uuid, uuid, text, bigint, text, bigint, text, numeric) from public, anon, authenticated;
revoke execute on function public.handle_practice_attempt_elo() from public, anon, authenticated;
revoke execute on function public.handle_exercise_evaluation_elo() from public, anon, authenticated;
revoke execute on function public.handle_exam_question_score_elo() from public, anon, authenticated;
