-- Reusable, tenant-scoped retrieval-practice placements inside a lesson.
create table public.lesson_checkpoints (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  lesson_id integer not null references public.lessons(id) on delete cascade,
  exercise_id integer not null references public.exercises(id) on delete restrict,
  placement_type text not null check (placement_type in ('inline', 'video')),
  content_block_id text,
  video_timestamp_seconds integer,
  label text,
  allow_skip boolean not null default false,
  max_ai_attempts integer not null default 1 check (max_ai_attempts between 0 and 10),
  is_required boolean not null default true,
  is_enabled boolean not null default true,
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    (placement_type = 'inline' and content_block_id is not null and video_timestamp_seconds is null)
    or (placement_type = 'video' and content_block_id is null and video_timestamp_seconds is not null and video_timestamp_seconds >= 0)
  )
);

create unique index lesson_checkpoints_inline_placement_idx
  on public.lesson_checkpoints (lesson_id, content_block_id)
  where placement_type = 'inline';
create unique index lesson_checkpoints_video_placement_idx
  on public.lesson_checkpoints (lesson_id, video_timestamp_seconds)
  where placement_type = 'video';
create index lesson_checkpoints_lesson_enabled_idx
  on public.lesson_checkpoints (lesson_id, is_enabled);
create index lesson_checkpoints_tenant_exercise_idx
  on public.lesson_checkpoints (tenant_id, exercise_id);

-- Canonical event log for teacher-authored checkpoint attempts. This is kept
-- separate from practice_attempts, whose trigger grants XP to LLM drill rows.
create table public.lesson_checkpoint_attempts (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id integer not null references public.courses(course_id) on delete cascade,
  lesson_id integer not null references public.lessons(id) on delete cascade,
  checkpoint_id bigint not null references public.lesson_checkpoints(id) on delete cascade,
  exercise_id integer not null references public.exercises(id) on delete restrict,
  placement_source text not null check (placement_source in ('inline', 'video')),
  response jsonb not null default '{}'::jsonb,
  evaluation jsonb,
  score numeric(5,2),
  passed boolean,
  completed boolean not null default false,
  evaluator_type text not null check (evaluator_type in ('deterministic', 'ai', 'media', 'code', 'pending', 'fallback')),
  attempt_number integer not null check (attempt_number > 0),
  created_at timestamptz not null default now(),
  unique (user_id, checkpoint_id, attempt_number)
);

create index lesson_checkpoint_attempts_resume_idx
  on public.lesson_checkpoint_attempts (user_id, checkpoint_id, created_at desc);
create index lesson_checkpoint_attempts_teacher_metrics_idx
  on public.lesson_checkpoint_attempts (tenant_id, checkpoint_id, created_at desc);
create index lesson_checkpoint_attempts_user_lesson_idx
  on public.lesson_checkpoint_attempts (user_id, lesson_id, created_at desc);

alter table public.lesson_checkpoints enable row level security;
alter table public.lesson_checkpoint_attempts enable row level security;

create policy lesson_checkpoints_students_can_read_enrolled_lessons
  on public.lesson_checkpoints for select to authenticated
  using (
    is_enabled
    and exists (
      select 1 from public.lessons l
      join public.enrollments e on e.course_id = l.course_id
      where l.id = lesson_checkpoints.lesson_id
        and l.tenant_id = lesson_checkpoints.tenant_id
        and e.user_id = (select auth.uid())
        and e.status = 'active'
    )
  );

create policy lesson_checkpoints_teachers_manage_tenant
  on public.lesson_checkpoints for all to authenticated
  using (
    exists (
      select 1 from public.tenant_users tu
      where tu.user_id = (select auth.uid())
        and tu.tenant_id = lesson_checkpoints.tenant_id
        and tu.role in ('teacher', 'admin') and tu.status = 'active'
    )
  )
  with check (
    exists (
      select 1 from public.tenant_users tu
      where tu.user_id = (select auth.uid())
        and tu.tenant_id = lesson_checkpoints.tenant_id
        and tu.role in ('teacher', 'admin') and tu.status = 'active'
    )
  );

create policy lesson_checkpoint_attempts_students_read_own_rows
  on public.lesson_checkpoint_attempts for select to authenticated
  using (user_id = (select auth.uid()));

create policy lesson_checkpoint_attempts_students_insert_own_rows
  on public.lesson_checkpoint_attempts for insert to authenticated
  with check (
    user_id = (select auth.uid())
    and exists (
      select 1 from public.lesson_checkpoints c
      where c.id = lesson_checkpoint_attempts.checkpoint_id
        and c.tenant_id = lesson_checkpoint_attempts.tenant_id
        and c.lesson_id = lesson_checkpoint_attempts.lesson_id
        and c.exercise_id = lesson_checkpoint_attempts.exercise_id
    )
  );

create policy lesson_checkpoint_attempts_teachers_read_tenant
  on public.lesson_checkpoint_attempts for select to authenticated
  using (
    exists (
      select 1 from public.tenant_users tu
      where tu.user_id = (select auth.uid())
        and tu.tenant_id = lesson_checkpoint_attempts.tenant_id
        and tu.role in ('teacher', 'admin') and tu.status = 'active'
    )
  );
