-- practice_attempts: storage for AI-tutor-generated practice quizzes (Epic #348, issue #349).
-- LLM-authored drills — never teacher content (`exercises`) and never real grades
-- (`exam_submissions`). Attempts persist for weak-spot analysis (#351), drill lineage
-- (source_exercise_id → variations of a real exercise), and XP.

create table if not exists public.practice_attempts (
  id                 bigint generated by default as identity primary key,
  user_id            uuid        not null references auth.users(id) on delete cascade,
  tenant_id          uuid        not null references public.tenants(id) on delete cascade,
  course_id          bigint,
  lesson_id          bigint,
  source_exercise_id bigint      references public.exercises(id) on delete set null,
  topic              text        not null,
  questions          jsonb       not null,  -- LLM-generated questions incl. correct answers
  answers            jsonb       not null,  -- student answers + per-question correct flag
  score              numeric(5,2) not null,
  total_questions    integer     not null,
  correct_count      integer     not null,
  source             text        not null default 'mcp-tutor',
  created_at         timestamptz not null default now()
);

create index if not exists practice_attempts_user_recent_idx
  on public.practice_attempts (user_id, tenant_id, created_at desc);
create index if not exists practice_attempts_user_lesson_idx
  on public.practice_attempts (user_id, lesson_id);
create index if not exists practice_attempts_user_source_exercise_idx
  on public.practice_attempts (user_id, source_exercise_id, created_at desc);

-- RLS: same authoritative pattern as exercise_evaluations — student owns their rows;
-- teacher/admin read is derived from active `tenant_users` membership bound to auth.uid(),
-- NOT the client-settable x-tenant-id header.
alter table public.practice_attempts enable row level security;

create policy students_own_practice_attempts on public.practice_attempts
  for all
  using ( user_id = (select auth.uid()) )
  with check ( user_id = (select auth.uid()) );

create policy teachers_view_tenant_practice_attempts on public.practice_attempts
  for select
  using (
    exists (
      select 1
      from public.tenant_users tu
      where tu.user_id = (select auth.uid())
        and tu.tenant_id = practice_attempts.tenant_id
        and tu.role in ('teacher', 'admin')
        and tu.status = 'active'
    )
  );

-- XP: +15 per attempt, capped at 10 awarded attempts per user/tenant/day so the drill
-- loop can't be farmed (award_xp itself has no cap mechanics; gamification daily_caps
-- isn't wired into it — in-trigger cap is the cheap equivalent).
create or replace function public.handle_practice_attempt_xp()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_awards_today int;
begin
  select count(*) into v_awards_today
  from public.gamification_xp_transactions
  where user_id = new.user_id
    and tenant_id = new.tenant_id
    and action_type = 'practice_attempt'
    and created_at >= date_trunc('day', now());

  if v_awards_today < 10 then
    perform award_xp(new.user_id, 'practice_attempt', 15, new.id::text, 'practice_attempt', new.tenant_id);
  end if;

  return new;
end;
$$;

-- Trigger-only function — not meant to be a PostgREST RPC (advisor:
-- anon_security_definer_function_executable; matches fix_advisor_security_findings).
revoke execute on function public.handle_practice_attempt_xp() from public, anon, authenticated;

create trigger trg_practice_attempt_xp
  after insert on public.practice_attempts
  for each row execute function public.handle_practice_attempt_xp();
