-- review_cards: flashcards + SM-2 spaced repetition (Epic #348, issue #355).
-- LLM-authored flashcards from lesson material; the SM-2 scheduler state
-- (ease/interval/repetitions/due_at) lives on the row and is updated ONLY by
-- lms_grade_review server-side — never by the host LLM directly.

create table if not exists public.review_cards (
  id               bigint generated by default as identity primary key,
  user_id          uuid        not null references auth.users(id) on delete cascade,
  tenant_id        uuid        not null references public.tenants(id) on delete cascade,
  course_id        bigint,
  lesson_id        bigint,
  front            text        not null,
  back             text        not null,
  ease             numeric(4,2) not null default 2.5,
  interval_days    integer     not null default 0,
  repetitions      integer     not null default 0,
  due_at           timestamptz not null default now(),
  last_reviewed_at timestamptz,
  suspended        boolean     not null default false,
  created_at       timestamptz not null default now()
);

create index if not exists review_cards_user_due_idx
  on public.review_cards (user_id, tenant_id, due_at);

-- RLS: same authoritative pattern as practice_attempts — student owns their
-- rows (ALL); teacher/admin read derived from active tenant_users membership
-- bound to auth.uid(), NOT the client-settable x-tenant-id header.
alter table public.review_cards enable row level security;

create policy students_own_review_cards on public.review_cards
  for all
  using ( user_id = (select auth.uid()) )
  with check ( user_id = (select auth.uid()) );

create policy teachers_view_tenant_review_cards on public.review_cards
  for select
  using (
    exists (
      select 1
      from public.tenant_users tu
      where tu.user_id = (select auth.uid())
        and tu.tenant_id = review_cards.tenant_id
        and tu.role in ('teacher', 'admin')
        and tu.status = 'active'
    )
  );
