-- study_goals: weekly study plan the student and AI tutor maintain together
-- (Epic #348, issue #359). One row per goal; a week's plan is the set of rows
-- sharing (user_id, tenant_id, week_start). lms_set_study_plan replaces the
-- caller's rows for a week; lms_complete_study_goal checks one off.

create table if not exists public.study_goals (
  id         bigint generated by default as identity primary key,
  user_id    uuid        not null references auth.users(id) on delete cascade,
  tenant_id  uuid        not null references public.tenants(id) on delete cascade,
  course_id  bigint,
  title      text        not null,
  kind       text        not null
    check (kind in ('lesson', 'practice', 'review', 'exam_prep', 'custom')),
  target_ref jsonb,
  week_start date        not null,
  done       boolean     not null default false,
  done_at    timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists study_goals_user_week_idx
  on public.study_goals (user_id, tenant_id, week_start);

-- RLS: same authoritative pattern as practice_attempts — student owns their
-- rows (ALL); teacher/admin read derived from active tenant_users membership
-- bound to auth.uid(), NOT the client-settable x-tenant-id header.
alter table public.study_goals enable row level security;

create policy students_own_study_goals on public.study_goals
  for all
  using ( user_id = (select auth.uid()) )
  with check ( user_id = (select auth.uid()) );

create policy teachers_view_tenant_study_goals on public.study_goals
  for select
  using (
    exists (
      select 1
      from public.tenant_users tu
      where tu.user_id = (select auth.uid())
        and tu.tenant_id = study_goals.tenant_id
        and tu.role in ('teacher', 'admin')
        and tu.status = 'active'
    )
  );
