// AUTO-GENERATED by scripts/gen-puck-fields-manifest.ts (run from the repo root:
// npx tsx scripts/gen-puck-fields-manifest.ts). Do NOT edit by hand.

export const EXCLUDED_COMPONENTS: readonly string[] = [
  "Section",
  "Container",
  "Columns",
  "Grid",
  "Card",
  "Spacer",
  "Divider",
  "IconBlock",
  "BadgeBlock",
  "Navbar",
  "BreadcrumbBlock",
  "Heading",
  "ButtonBlock"
]

export const COMPONENT_DESCRIPTIONS: Record<string, string> = {
  "TextBlock": "Standalone paragraph of body text.",
  "Image": "Standalone image (https URL).",
  "Video": "Embedded YouTube/Vimeo video (https URL).",
  "HeroBlock": "Hero: headline, subtitle, up to two CTAs. Opens most pages.",
  "FeaturesGrid": "Benefits grid: emoji icon, title, description each.",
  "CourseGrid": "The school's real courses; empty courseIds = latest.",
  "PricingTable": "The school's real plans. planIds pins a subset; empty shows all.",
  "TestimonialGrid": "Real reviews (source \"live\"). \"manual\" only for quotes the user gave.",
  "FaqAccordion": "Expandable FAQ. Full, specific answers.",
  "FaqSplit": "Two-column FAQ: heading left, questions right.",
  "StatsCounter": "Statistics row. Prefer useLiveStats; never invent numbers.",
  "StatsBand": "Statistics band. Prefer useLiveStats.",
  "AnimatedStats": "Count-up statistics. Prefer useLiveStats.",
  "CtaBlock": "Call to action with buttons.",
  "CtaBanner": "Closing call to action, last before the Footer.",
  "ContactForm": "Contact form section.",
  "LogoCloud": "Partner logos the user supplied.",
  "LogoMarquee": "Scrolling partner logos the user supplied.",
  "Banner": "Thin announcement banner near the top.",
  "TeamGrid": "Real team members the user named; no invented credentials.",
  "ImageGallery": "Gallery of images.",
  "SocialProof": "Ratings/counts strip. Real figures only.",
  "EnrollCta": "Single-course enroll band; the label shows the price or \"free\".",
  "CatalogBrowser": "Searchable browser over all courses.",
  "ShinyEyebrow": "Small label above a hero headline.",
  "ContentFeature": "Text + image, optional pull-quote.",
  "Header": "Logo, nav links, CTA. First block.",
  "Footer": "Link columns and copyright. Last block.",
  "CourseHero": "Hero for one course page: title, cover, price, rating, instructor. Facts come from the course; write no prices, counts or names.",
  "CourseCurriculum": "The course's real lesson list with free-preview links.",
  "CourseOutcomes": "What you'll learn. The course's objectives win; items are the fallback.",
  "CoursePricingCard": "Price card for one course or product (productId wins). Price is live.",
  "ProductGrid": "Cards for active products/bundles. Empty productIds shows the newest.",
  "InstructorCard": "The course author's real name, photo and bio. Never write credentials."
}

export const LANDING_PAGE_CRAFT_GUIDE = "HOW TO BUILD A GREAT LANDING PAGE:\n1. Length & flow. Produce a COMPLETE page of 6–9 sections, not a stub. A strong default flow:\n   HeroBlock → StatsBand (or AnimatedStats) → FeaturesGrid → ContentFeature → TestimonialGrid\n   → PricingTable (if relevant) → FaqAccordion → CtaBanner. Adapt to the user's request.\n2. Always open with HeroBlock and always close with CtaBanner (the final sign-up driver).\n3. Prefer the rich marketing sections (HeroBlock, StatsBand, AnimatedStats, FeaturesGrid,\n   ContentFeature, TestimonialGrid, PricingTable, TeamGrid, FaqAccordion, CtaBanner) over the\n   bare primitives (Heading, TextBlock, ButtonBlock) — primitives are for one-off touches.\n4. Write REAL, specific, benefit-driven copy in the page's language — distinct feature titles and full FAQ answers. Use live-data widgets for stats and pricing.\n   Never invent student counts, outcomes, testimonials, or prices; omit proof the user has\n   not supplied. Never use filler like \"Feature\" or \"Lorem ipsum\".\n5. Theming: inherit the school theme by default. Leave accentColor, backgroundColor, and\n   color empty or omitted so the school's current palette applies. Keep the inherited\n   heading/body fonts and component corners; use borderRadius=\"school\" when supported.\n   Only set explicit colors or corners when the user requests an override. Keep layout\n   surfaces flat, without decorative shadows, gradient text, or hover-lift effects.\n6. Use real CTA hrefs: \"/auth/sign-up\" for sign-up, \"/courses\" to browse, \"#features\"/\"#faq\"\n   for in-page anchors. Give the hero a primary AND secondary CTA.\n7. Spacing: let blocks use their defaults; only set paddingY/marginY when a section needs more\n   breathing room. Don't set every spacing prop on every block.\n\nUse ONLY the documented component names and props."
