// AUTO-GENERATED by scripts/gen-puck-fields-manifest.ts (run from the repo root:
// npx tsx scripts/gen-puck-fields-manifest.ts). Do NOT edit by hand.

export const EXCLUDED_COMPONENTS: readonly string[] = [
  "Section",
  "Container",
  "Columns",
  "Grid",
  "Card",
  "Spacer",
  "Divider",
  "IconBlock",
  "BadgeBlock"
]

export const COMPONENT_DESCRIPTIONS: Record<string, string> = {
  "Heading": "A standalone heading/title. Use sparingly between sections, not as a full section.",
  "TextBlock": "A standalone paragraph of body text.",
  "Image": "A standalone image.",
  "ButtonBlock": "A standalone call-to-action button.",
  "Video": "An embedded video (YouTube/Vimeo/file URL).",
  "HeroBlock": "Top-of-page hero banner with a large headline, subtitle, and up to two CTA buttons. Use as the FIRST block of almost every page.",
  "FeaturesGrid": "A grid of features/benefits, each with an icon, title, and description. Use to explain what the course/school offers.",
  "CourseGrid": "A grid of the tenant's real courses (data-bound). Use when the page should showcase actual courses. Leave courseIds empty so it shows the latest published courses — do NOT invent course IDs; curation is a human-only step.",
  "PricingTable": "Side-by-side pricing plans with features and CTAs.",
  "TestimonialGrid": "A grid of student testimonials with name, role, and quote.",
  "FaqAccordion": "An expandable FAQ accordion. Good general-purpose FAQ.",
  "FaqSplit": "A two-column FAQ: heading on the left, questions on the right.",
  "StatsCounter": "A row of key statistics (value + label).",
  "StatsBand": "A horizontal band of headline statistics with an optional heading/subtitle. Use for social proof.",
  "AnimatedStats": "Statistics that count up on scroll into view; each has a numeric value plus prefix/suffix.",
  "CtaBlock": "A call-to-action section with heading and button(s).",
  "CtaBanner": "A centered closing call-to-action banner with heading, subtitle, and one or two buttons. Use as the LAST block to drive sign-ups.",
  "ContactForm": "A contact form section.",
  "LogoCloud": "A static row of partner/brand logos for trust.",
  "LogoMarquee": "An animated, infinitely-scrolling row of partner/brand logos.",
  "Banner": "A thin announcement/promo banner, often near the top.",
  "TeamGrid": "A grid of team members/instructors with photo, name, and role.",
  "ImageGallery": "A gallery of images.",
  "SocialProof": "A social-proof strip (ratings, counts, short quotes).",
  "EnrollCta": "A single-course call-to-action band with a headline, subtext, and an enroll button. Leave courseId empty (you cannot know real course IDs) — it then links to the full catalog; targeting a specific course is a human-only step.",
  "CatalogBrowser": "A filterable, paginated browser over the tenant's real courses with search and an All/Free/Paid filter. Use when the page should let visitors explore the whole catalog.",
  "ShinyEyebrow": "A small animated eyebrow/announcement label, placed above a hero headline.",
  "ContentFeature": "A text + image content section with an optional pull-quote; image can be on the left or right.",
  "Header": "A page header with logo and nav links.",
  "Footer": "A page footer with link columns and copyright.",
  "Navbar": "A navigation bar.",
  "BreadcrumbBlock": "A breadcrumb trail."
}

export const LANDING_PAGE_CRAFT_GUIDE = "HOW TO BUILD A GREAT LANDING PAGE:\n1. Length & flow. Produce a COMPLETE page of 6–9 sections, not a stub. A strong default flow:\n   HeroBlock → StatsBand (or AnimatedStats) → FeaturesGrid → ContentFeature → TestimonialGrid\n   → PricingTable (if relevant) → FaqAccordion → CtaBanner. Adapt to the user's request.\n2. Always open with HeroBlock and always close with CtaBanner (the final sign-up driver).\n3. Prefer the rich marketing sections (HeroBlock, StatsBand, AnimatedStats, FeaturesGrid,\n   ContentFeature, TestimonialGrid, PricingTable, TeamGrid, FaqAccordion, CtaBanner) over the\n   bare primitives (Heading, TextBlock, ButtonBlock) — primitives are for one-off touches.\n4. Write REAL, specific, benefit-driven copy in the page's language — concrete numbers in\n   stats, full sentences in testimonials and FAQ answers, distinct feature titles. Never use\n   placeholder text like \"Feature\" or \"Lorem ipsum\". Fill every array with 3+ rich items.\n5. Theming: pick ONE tasteful brand accent and pass it as \"accentColor\" on blocks that accept\n   it (HeroBlock.backgroundColor, FeaturesGrid/StatsCounter/FaqAccordion.accentColor) — use an\n   OKLCH or hex value that fits the topic (e.g. a warm tone for photography). Keep it\n   consistent across the page. Leave it out to inherit the tenant's default brand color.\n6. Use real CTA hrefs: \"/auth/sign-up\" for sign-up, \"/courses\" to browse, \"#features\"/\"#faq\"\n   for in-page anchors. Give the hero a primary AND secondary CTA.\n7. Spacing: let blocks use their defaults; only set paddingY/marginY when a section needs more\n   breathing room. Don't set every spacing prop on every block.\n\nUse ONLY the documented component names and props."
